### ISSUE TITLE
Using wrong syntax for 'greater than or equal' operator breaks keyword 'Get Value From Json'

### ISSUE THREAD

**Issue by Tset-Noitamotua** [robotframework-thailand/robotframework-jsonlibrary#9] opened 2017-10-08 13:49 UTC
Example of misstyped 'greater than or equal' operator (take NOTE of `price=>8.99`  which is wrong  - it should be `>=` - nevertheless it breaks the keyword)

```robotframework
Get all books with price biger than or equal to 8.99
    [Documentation]    `?()`	applies a filter (script) expression.
    Get Value From Json    ${bookstore_data}    $..book[?(@.price=>8.99)]
```

## error
```shell
Parse error at 1:18 near token > (FILTER_OP)	
15:34:05.578	DEBUG	Traceback (most recent call last):
  File "c:\python_virtual_envs\api_requests\lib\site-packages\JSONLibrary\JSONLibraryKeywords.py", line 77, in get_value_from_json
    json_path_expr = parse(json_path)
  File "c:\python_virtual_envs\api_requests\lib\site-packages\jsonpath_rw_ext\parser.py", line 179, in parse
    return ExtentedJsonPathParser(debug=debug).parse(path)
  File "c:\python_virtual_envs\api_requests\lib\site-packages\jsonpath_rw\parser.py", line 32, in parse
    return self.parse_token_stream(lexer.tokenize(string))
  File "c:\python_virtual_envs\api_requests\lib\site-packages\jsonpath_rw\parser.py", line 55, in parse_token_stream
    return new_parser.parse(lexer = IteratorToTokenStream(token_iterator))
  File "c:\python_virtual_envs\api_requests\lib\site-packages\ply\yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "c:\python_virtual_envs\api_requests\lib\site-packages\ply\yacc.py", line 1199, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "c:\python_virtual_envs\api_requests\lib\site-packages\ply\yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "c:\python_virtual_envs\api_requests\lib\site-packages\jsonpath_rw\parser.py", line 69, in p_error
    raise Exception('Parse error at %s:%s near token %s (%s)' % (t.lineno, t.col, t.value, t.type))
```

Same applies in the other direction with misstyped 'less than or equal' operator `=<` 
```shell
Parse error at 1:18 near token < (FILTER_OP)
```

**Comment by elrandira** [comment] 2022-05-10 14:41
it works as intended. The error is generated by the library jsonpath_ng that is implemented in robotframework-jsonlibrary. The syntax =< is not recognized as it is considered here as another action: it expects something else after the '=' character.

I propose to close this issue.

**Closed as completed** 2022-05-17 07:16 UTC
