### ISSUE TITLE
AND operator not working in jsonPath

### ISSUE THREAD

**Issue by kaamos91** [robotframework-thailand/robotframework-jsonlibrary#19] opened 2019-07-15 12:17 UTC
Hi!
I tried to use a multiple condition filter in a jsonPath
like:
$[?(@.invoiceNum='${value1}' && @.issueNum=${value2})].issueDate
but the and operator doesn't work (i guess the or operator is the same).
I get a parse error: 
Invalid JSONPath query '$[?(@.invoiceNum='1111111' && @.issueNum=1)].issueDate': Parse error at 1:28 near token & (&)

**Comment by elrandira** [comment] 2022-05-10 14:37
I know this is 3years old but I couldn't reproduce your error with the following syntax and [Goessner's data model](https://goessner.net/articles/JsonPath/).

Note that the keyword for AND is just one '&', not two

```
*** Test Cases ***
test and in jsonpath
    ${obj}=    Load JSON From File  ${CURDIR}/bookstore.json
    ${value}=  Get Value From Json  ${obj}  $..book[?(@.category='fiction' & @.price>10)].title
    log to console  ${value}
```

Execution:
```
==============================================================================
Test
==============================================================================
test and in jsonpath                                                  ...
['Sword of Honour', 'The Lord of the Rings']
test and in jsonpath                                                  | PASS |
------------------------------------------------------------------------------
Test                                                                  | PASS |
1 test, 1 passed, 0 failed
==============================================================================
```

I propose to close this issue

**Closed as completed** 2022-05-11 08:41 UTC
